### ISSUE TITLE
Bad layout

### ISSUE THREAD

**Issue by SoKnight** [Sh6abrA/Sh6abrA.github.io#1]
Сайт ужасен, на FHD всё съезжает, прошу исправить!
![image](https://github.com/Sh6abrA/Sh6abrA.github.io/assets/46436573/5f680960-0ca3-49b7-b50c-8f0b197274da)

**Comment by Sh6abrA** [comment]
Зачем ты ваще зашел? Это тестовый сайтик был. Он даже к беку не подключен
![image](https://github.com/Sh6abrA/Sh6abrA.github.io/assets/47980718/cb1cfa6d-aad5-4e22-a7a9-8429597ff0b1)
 Исправил кста в одну строчку проверяй
